- pkg:deb/debian/prometheus-mqtt-exporter@0.1.4-2%2Bb7?arch=amd64
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.4-2%2Bb7?arch=arm64
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.4-2%2Bb7?arch=armhf
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.4-2%2Bb7?arch=i386
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb14?arch=riscv64
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb18?arch=amd64
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb18?arch=arm64
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb18?arch=armel
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb18?arch=armhf
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb18?arch=i386
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb18?arch=mips64el
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb18?arch=ppc64el
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb18?arch=s390x
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb4?arch=amd64
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb4?arch=arm64
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb4?arch=armel
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb4?arch=armhf
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb4?arch=i386
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb4?arch=mips64el
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb4?arch=mipsel
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb4?arch=ppc64el
- pkg:deb/debian/prometheus-mqtt-exporter@0.1.7-1%2Bb4?arch=s390x
