- pkg:deb/debian/cloud-initramfs-rescuevol@0.18.debian13%2Bdeb12u1?arch=all
- pkg:deb/debian/cloud-initramfs-rescuevol@0.18.debian14?arch=all
- pkg:deb/debian/cloud-initramfs-rescuevol@0.18.debian8?arch=all
