- pkg:deb/debian/prometheus-process-exporter@0.7.10-3%2Bb5?arch=amd64
- pkg:deb/debian/prometheus-process-exporter@0.7.10-3%2Bb5?arch=arm64
- pkg:deb/debian/prometheus-process-exporter@0.7.10-3%2Bb5?arch=armel
- pkg:deb/debian/prometheus-process-exporter@0.7.10-3%2Bb5?arch=armhf
- pkg:deb/debian/prometheus-process-exporter@0.7.10-3%2Bb5?arch=i386
- pkg:deb/debian/prometheus-process-exporter@0.7.10-3%2Bb5?arch=mips64el
- pkg:deb/debian/prometheus-process-exporter@0.7.10-3%2Bb5?arch=mipsel
- pkg:deb/debian/prometheus-process-exporter@0.7.10-3%2Bb5?arch=ppc64el
- pkg:deb/debian/prometheus-process-exporter@0.7.10-3%2Bb5?arch=s390x
- pkg:deb/debian/prometheus-process-exporter@0.7.5-3%2Bb5?arch=amd64
- pkg:deb/debian/prometheus-process-exporter@0.7.5-3%2Bb5?arch=arm64
- pkg:deb/debian/prometheus-process-exporter@0.7.5-3%2Bb5?arch=armhf
- pkg:deb/debian/prometheus-process-exporter@0.7.5-3%2Bb5?arch=i386
- pkg:deb/debian/prometheus-process-exporter@0.8.5-1?arch=amd64
- pkg:deb/debian/prometheus-process-exporter@0.8.5-1?arch=arm64
- pkg:deb/debian/prometheus-process-exporter@0.8.5-1?arch=armel
- pkg:deb/debian/prometheus-process-exporter@0.8.5-1?arch=armhf
- pkg:deb/debian/prometheus-process-exporter@0.8.5-1?arch=i386
- pkg:deb/debian/prometheus-process-exporter@0.8.5-1?arch=ppc64el
- pkg:deb/debian/prometheus-process-exporter@0.8.5-1?arch=riscv64
- pkg:deb/debian/prometheus-process-exporter@0.8.5-1?arch=s390x
- pkg:deb/debian/prometheus-process-exporter@0.8.7-1?arch=amd64
- pkg:deb/debian/prometheus-process-exporter@0.8.7-1?arch=arm64
- pkg:deb/debian/prometheus-process-exporter@0.8.7-1?arch=armel
- pkg:deb/debian/prometheus-process-exporter@0.8.7-1?arch=armhf
- pkg:deb/debian/prometheus-process-exporter@0.8.7-1?arch=i386
- pkg:deb/debian/prometheus-process-exporter@0.8.7-1?arch=mips64el
- pkg:deb/debian/prometheus-process-exporter@0.8.7-1?arch=ppc64el
- pkg:deb/debian/prometheus-process-exporter@0.8.7-1?arch=riscv64
- pkg:deb/debian/prometheus-process-exporter@0.8.7-1?arch=s390x
