- pkg:deb/debian/python3-django-prometheus@2.1.0-1?arch=all
- pkg:deb/debian/python3-django-prometheus@2.2.0-1?arch=all
- pkg:deb/debian/python3-django-prometheus@2.3.1-2?arch=all
- pkg:deb/debian/python3-django-prometheus@2.4.1-1?arch=all
