- pkg:deb/debian/prometheus-postfix-exporter@0.12.1-1?arch=amd64
- pkg:deb/debian/prometheus-postfix-exporter@0.12.1-1?arch=arm64
- pkg:deb/debian/prometheus-postfix-exporter@0.12.1-1?arch=armel
- pkg:deb/debian/prometheus-postfix-exporter@0.12.1-1?arch=armhf
- pkg:deb/debian/prometheus-postfix-exporter@0.12.1-1?arch=i386
- pkg:deb/debian/prometheus-postfix-exporter@0.12.1-1?arch=mips64el
- pkg:deb/debian/prometheus-postfix-exporter@0.12.1-1?arch=ppc64el
- pkg:deb/debian/prometheus-postfix-exporter@0.12.1-1?arch=riscv64
- pkg:deb/debian/prometheus-postfix-exporter@0.12.1-1?arch=s390x
- pkg:deb/debian/prometheus-postfix-exporter@0.2.0-3%2Bb6?arch=amd64
- pkg:deb/debian/prometheus-postfix-exporter@0.2.0-3%2Bb6?arch=arm64
- pkg:deb/debian/prometheus-postfix-exporter@0.2.0-3%2Bb6?arch=armhf
- pkg:deb/debian/prometheus-postfix-exporter@0.2.0-3%2Bb6?arch=i386
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-4%2Bb3?arch=amd64
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-4%2Bb3?arch=arm64
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-4%2Bb3?arch=armel
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-4%2Bb3?arch=armhf
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-4%2Bb3?arch=i386
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-4%2Bb3?arch=mips64el
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-4%2Bb3?arch=mipsel
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-4%2Bb3?arch=ppc64el
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-4%2Bb3?arch=s390x
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-5%2Bb8?arch=amd64
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-5%2Bb8?arch=arm64
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-5%2Bb8?arch=armel
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-5%2Bb8?arch=armhf
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-5%2Bb8?arch=i386
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-5%2Bb8?arch=ppc64el
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-5%2Bb8?arch=riscv64
- pkg:deb/debian/prometheus-postfix-exporter@0.3.0-5%2Bb8?arch=s390x
