- pkg:deb/debian/golang-github-mcuadros-go-gin-prometheus-dev@0.1.0%2Bgit20190723.c7374e9-3?arch=all
- pkg:deb/debian/golang-github-mcuadros-go-gin-prometheus-dev@0.1.0%2Bgit20190723.c7374e9-5?arch=all
