- pkg:deb/debian/prometheus-nextcloud-exporter@0.6.0-1%2Bb3?arch=amd64
- pkg:deb/debian/prometheus-nextcloud-exporter@0.6.0-1%2Bb3?arch=arm64
- pkg:deb/debian/prometheus-nextcloud-exporter@0.6.0-1%2Bb3?arch=armel
- pkg:deb/debian/prometheus-nextcloud-exporter@0.6.0-1%2Bb3?arch=armhf
- pkg:deb/debian/prometheus-nextcloud-exporter@0.6.0-1%2Bb3?arch=i386
- pkg:deb/debian/prometheus-nextcloud-exporter@0.6.0-1%2Bb3?arch=mips64el
- pkg:deb/debian/prometheus-nextcloud-exporter@0.6.0-1%2Bb3?arch=mipsel
- pkg:deb/debian/prometheus-nextcloud-exporter@0.6.0-1%2Bb3?arch=ppc64el
- pkg:deb/debian/prometheus-nextcloud-exporter@0.6.0-1%2Bb3?arch=s390x
- pkg:deb/debian/prometheus-nextcloud-exporter@0.8.0-2?arch=amd64
- pkg:deb/debian/prometheus-nextcloud-exporter@0.8.0-2?arch=arm64
- pkg:deb/debian/prometheus-nextcloud-exporter@0.8.0-2?arch=armel
- pkg:deb/debian/prometheus-nextcloud-exporter@0.8.0-2?arch=armhf
- pkg:deb/debian/prometheus-nextcloud-exporter@0.8.0-2?arch=i386
- pkg:deb/debian/prometheus-nextcloud-exporter@0.8.0-2?arch=mips64el
- pkg:deb/debian/prometheus-nextcloud-exporter@0.8.0-2?arch=ppc64el
- pkg:deb/debian/prometheus-nextcloud-exporter@0.8.0-2?arch=riscv64
- pkg:deb/debian/prometheus-nextcloud-exporter@0.8.0-2?arch=s390x
